version: "3"
include:
  - docker-compose-db.yaml
services:  
  postgres:
    image: postgres:16.0
    restart: always
    volumes:
      - "./initdb.d-postgres:/docker-entrypoint-initdb.d:ro"
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "9432:5432"
  postgraphile:
    image: graphile/postgraphile:4
    restart: always
    ports:
      - "8081:5000"
    depends_on:
      - postgres
    command: "--watch --simple-collections only"
    environment:
      DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
  graphql-mesh:
    build: .
    restart: always
    ports:
      - "8000:4000"
    depends_on:
      - postgraphile
    volumes:
      - "./.meshrc.yaml:/root/.meshrc.yaml:ro"
